In [1]:
from metaheuristic import *
import numpy as np

In [5]:
X = np.array([1,2,3,4,5])

S1 = op.select_random(X, n=1)

S1

array([[1],
       [5],
       [4],
       [5],
       [1]])

In [8]:
# S1,S2 = None
S1 = op.select_random_exclusive(X)
S1

array([[3],
       [4],
       [1],
       [4],
       [1]])

In [9]:
# S1 = OK S2 = None
S2 = op.select_random_exclusive(X, S1)
S2

array([[2],
       [5],
       [3],
       [2],
       [4]])

In [10]:
# S1,S2 = OK
S3 = op.select_random_exclusive(X, S1, S2)
S3

array([[4],
       [1],
       [5],
       [1],
       [2]])

In [21]:
sum([a==b==c for a,b,c in zip(S1, S2, S3)])

array([0])